/*
 * The MIT License
 *
 * Copyright 2019 Pityubak.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.pityubak.gamelibrary.misc;

/**
 *
 * @author Pityubak
 */
public enum ColorType {
    NONE,
    RED,
    GREEN,
    BLUE,
    YELLOW,
    CYAN,
    MAGENTA,
    WHITE,
    BLACK,
    GRAY,
    LIGHT_GRAY,
    DARK_GRAY,
    ORANGE,
    PINK,
    LIME,
    OLIVE,
    PURPLE,
    TEAL,
    NAVY,
    MAROON,
    DARK_RED,
    BROWN,
    FIREBRICK,
    CRIMSON,
    TOMATO,
    CORAL,
    INDIAN_RED,
    LIGHT_CORAL,
    DARK_SALMON,
    SALMON,
    LIGHT_SALMON,
    ORANGE_RED,
    DARK_ORANGE,
    GOLD,
    DARK_GOLDEN_ROD,
    GOLDEN_ROD,
    LIGHT_GOLDEN_ROD,
    PALE_GOLDEN_ROD,
    DARK_KHAKI,
    KHAKI,
    YELLOW_GREEN,
    DARK_OLIVE_GREEN,
    OLIVE_DRAB,
    LAWN_GREEN,
    CHART_REUSE,
    GREEN_YELLOW,
    DARK_GREEN,
    FORREST_GREEN,
    LIME_GREEN,
    LIGHT_GREEN,
    PALE_GREEN,
    DARK_SEA_GREEN,
    MEDIUM_SPRING_GREEN,
    SPRING_GREEN,
    SEA_GREEN,
    MEDIUM_AQUA_MARINE,
    MEDIUM_SEA_GREEN,
    LIGHT_SEA_GREEN,
    DARK_SLATE_GRAY,
    DARK_CYAN,
    AQUA,
    LIGHT_CYAN,
    DARK_TURQUOISE,
    TURQUOISE,
    MEDIUM_TURQUOISE,
    PALE_TURQUOISE,
    AQUA_MARINE,
    POWDER_BLUE,
    CADET_BLUE,
    STEEL_BLUE,
    CORN_FLOWER_BLUE,
    DEEP_SKY_BLUE,
    DODGER_BLUE,
    LIGHT_BLUE,
    SKY_BLUE,
    LIGHT_SKY_BLUE,
    MIDNIGHT_BLUE,
    DARK_BLUE,
    MEDIUM_BLUE,
    ROYAL_BLUE,
    BLUE_VIOLET,
    INDIGO,
    DARK_SLATE_BLUE,
    SLATE_BLUE,
    MEDIUM_SLATE_BLUE,
    MEDIUM_PURPLE,
    DARK_MAGENTA,
    DARK_VIOLET,
    DARK_ORCHID,
    MEDIUM_ORCHID,
    THISTLE,
    PLUM,
    VIOLET,
    ORCHID,
    MEDIUM_VIOLET_RED,
    PALE_VIOLET_RED,
    DEEP_PINK,
    HOT_PINK,
    LIGHT_PINK,
    ANTIQUE_WHITE,
    BEIGE,
    BISQUE,
    BLANCHED_ALMOND,
    WHEAT,
    CORN_SILK,
    LEMON_CHIFFON,
    LIGHT_GOLDEN_ROD_YELLOW,
    LIGHT_YELLOW,
    SADDLE_BROWN,
    SIENNA,
    CHOCOLATE,
    PERU,
    SANDY_BROWN,
    BURLY_WOOD,
    TAN,
    ROSY_BROWN,
    MOCCASIN,
    NAVAJO_WHITE,
    PEACH_PUFF,
    MISTY_ROSE,
    LAVENDER_BLUSH,
    LINEN,
    OLD_LACE,
    PAPAYA_WHIP,
    SEA_SHELL,
    MINT_CREAM,
    SLATE_GRAY,
    LIGHT_SLATE_GRAY,
    LIGHT_STEEL_BLUE,
    LAVENDER,
    FLORAL_WHITE,
    ALICE_BLUE,
    GHOST_WHITE,
    HONEYDEW,
    IVORY,
    AZURE,
    SNOW,
    GAINSBORO,
    WHITE_SMOKE,
    SILVER
    

}
